---
title: "HW11"
format: pdf
editor: visual
---

# HW 11: Linear Models

```{r}

# Load data
crp <- read.csv("crp.csv")

# Design matrix including interaction term
X <- model.matrix(CRP ~ Age + Gender + Age*Gender, data = crp)

# Response vector
y <- crp$CRP

# Cross-product of the design matrix
cross <- t(X) %*% X

# Cross-product of design matrix and  y
cross_y <- t(X) %*% y

# Solve for  coefficients using Normal Equations
beta <- solve(cross) %*% cross_y
print(beta)

#standard lm method
fit <- lm(CRP ~ Age + Gender + Age*Gender, data = crp)
summary(fit)

```


```{r}

int <- lm(CRP ~ Age*Gender, data = crp)
add1 <- lm(CRP ~ Age, data = crp)
add2 <- lm(CRP ~ Age + Gender, data = crp)
add3 <- lm(CRP ~ Gender, data = crp)
allint <- lm(CRP ~ Age + Gender + Age*Gender, data = crp)

anova(int, add1, add2, add3, allint)

```

```{r}
anova(add2, add1, test="Chisq" )

null  <- logLik(add2)
MLE <- logLik(allint)

LRT <- (2*(MLE - null))

pval <- pchisq(LRT, df=1)
pval <- 1- pval

```

```{r}

summary(int, test="T")
anova(int, add2)


```







